// SPDX-License-Identifier: MPL-2.0
/**
 * `lolly completion bash|zsh|fish` - static shell-completion scripts (plans/202 WP5.1).
 *
 * `completion` was reserved as a verb ahead of this (args.ts, RESERVED_SUBCOMMANDS) so a
 * brand pack's tool id could never collide with it once it landed.
 *
 * The generated script completes:
 *   - verbs, read from RESERVED_SUBCOMMANDS - a verb added there later (the `tui` verb,
 *     for one) appears here automatically, with no second list to keep in sync
 *   - flags, from VALUE_FLAGS plus the four global boolean flags (--json, --quiet,
 *     --verbose, --strict)
 *   - tool ids, read from the active profile's catalog/tools/index.json at the moment
 *     the script is generated and baked into it as a flat word list
 *   - the flags whose value is a filesystem path (--output, --out-dir, --inputs,
 *     --template, --trust-anchor, --sign-key, --sign-cert, --rebuild) fall through to
 *     the shell's own file completion instead of a word list
 *
 * A generated script is a snapshot of the catalog at generation time: installing a
 * tool later needs `lolly completion <shell>` run again to see it. That is the same
 * trade every other CLI with a static completion script makes (git, cargo, kubectl);
 * there is no host.state or filesystem access from inside a shell's completion
 * function without a lot more plumbing than a small tool catalog is worth.
 */
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { repoRoot } from '@lolly-tools/node-shell/repo-root';
import { RESERVED_SUBCOMMANDS, VALUE_FLAGS } from './args.ts';

export type CompletionShell = 'bash' | 'zsh' | 'fish';
export const COMPLETION_SHELLS: readonly CompletionShell[] = ['bash', 'zsh', 'fish'];

const GLOBAL_BOOL_FLAGS = ['json', 'quiet', 'verbose', 'strict'] as const;

/** Value flags whose value is a filesystem path - completed as files/dirs, never a word list. */
const PATH_FLAGS = new Set([
  'output', 'out-dir', 'inputs', 'template', 'trust-anchor', 'sign-key', 'sign-cert', 'rebuild',
]);

/**
 * Tool ids from the active profile's catalog, best-effort. Empty (not thrown) when the
 * profile view has not been built yet - a fresh clone before `npm install`'s postinstall
 * has no catalog/tools/index.json - so the script still completes verbs and flags.
 */
export async function catalogToolIds(): Promise<string[]> {
  try {
    const indexPath = join(repoRoot(), 'catalog', 'tools', 'index.json');
    const index = JSON.parse(await readFile(indexPath, 'utf8')) as { tools: Array<{ id: string }> };
    return index.tools.map(t => t.id).filter(Boolean).sort();
  } catch {
    return [];
  }
}

function reservedVerbs(): string[] {
  return [...RESERVED_SUBCOMMANDS];
}

function wordFlagNames(): string[] {
  const names: string[] = [];
  for (const f of VALUE_FLAGS) if (!PATH_FLAGS.has(f)) names.push(`--${f}`);
  for (const f of GLOBAL_BOOL_FLAGS) names.push(`--${f}`);
  return names;
}

function pathFlagNames(): string[] {
  return [...PATH_FLAGS].map(f => `--${f}`);
}

/** Build the bare word lists a completion script needs, shared by all three shells. */
function completionWords(toolIds: string[]) {
  return {
    verbs: reservedVerbs(),
    flags: wordFlagNames(),
    pathFlags: pathFlagNames(),
    tools: toolIds,
  };
}

function bashScript(toolIds: string[]): string {
  const w = completionWords(toolIds);
  const pathCases = w.pathFlags.join('|');
  return `# lolly bash completion
# Generated by \`lolly completion bash\`. Install with:
#   lolly completion bash > /usr/local/etc/bash_completion.d/lolly   (Homebrew bash-completion)
# or source it directly from your shell profile.
_lolly_complete() {
  local cur prev words cword
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  local verbs="${w.verbs.join(' ')}"
  local tools="${w.tools.join(' ')}"
  local flags="${w.flags.join(' ')}"
  local pathflags="${w.pathFlags.join(' ')}"
  case "\${prev}" in
    ${pathCases})
      COMPREPLY=( $(compgen -f -- "\${cur}") )
      return 0
      ;;
  esac
  if [[ "\${cur}" == -* ]]; then
    COMPREPLY=( $(compgen -W "\${flags} \${pathflags}" -- "\${cur}") )
    return 0
  fi
  if [[ \${COMP_CWORD} -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "\${verbs} \${tools}" -- "\${cur}") )
    return 0
  fi
}
complete -F _lolly_complete lolly
`;
}

function zshScript(toolIds: string[]): string {
  const w = completionWords(toolIds);
  const pathFlagsAlt = w.pathFlags.join('|');
  return `#compdef lolly
# lolly zsh completion. Generated by \`lolly completion zsh\`. Install by saving this to
# a directory on your $fpath as _lolly (e.g. ~/.zsh/completions/_lolly), then
# \`autoload -U compinit && compinit\` in your .zshrc.
_lolly() {
  local -a verbs tools flags pathflags
  verbs=(${w.verbs.map(v => `'${v}'`).join(' ')})
  tools=(${w.tools.map(t => `'${t}'`).join(' ')})
  flags=(${w.flags.map(f => `'${f}'`).join(' ')})
  pathflags=(${w.pathFlags.map(f => `'${f}'`).join(' ')})

  if [[ "\${words[CURRENT-1]}" == @(${pathFlagsAlt}) ]]; then
    _files
    return
  fi

  if [[ "\${words[CURRENT]}" == -* ]]; then
    _describe 'flag' flags
    _describe 'flag' pathflags
    return
  fi

  if (( CURRENT == 2 )); then
    _describe 'command' verbs
    _describe 'tool' tools
  fi
}
_lolly "\$@"
`;
}

function fishScript(toolIds: string[]): string {
  const w = completionWords(toolIds);
  const lines: string[] = [
    '# lolly fish completion. Generated by `lolly completion fish`. Install by saving',
    '# this to ~/.config/fish/completions/lolly.fish.',
    '',
    'complete -c lolly -f',
  ];
  for (const v of w.verbs) {
    lines.push(`complete -c lolly -n "__fish_use_subcommand" -a "${v}"`);
  }
  for (const t of w.tools) {
    lines.push(`complete -c lolly -n "__fish_use_subcommand" -a "${t}" -d "tool"`);
  }
  for (const f of w.flags) {
    lines.push(`complete -c lolly -l "${f.replace(/^--/, '')}"`);
  }
  for (const f of w.pathFlags) {
    lines.push(`complete -c lolly -l "${f.replace(/^--/, '')}" -r -F`);
  }
  return lines.join('\n') + '\n';
}

/** Render the completion script for one shell. Reads the catalog itself (best-effort,
 *  see catalogToolIds); callers do not need to fetch tool ids separately. */
export async function generateCompletion(shell: CompletionShell): Promise<string> {
  const toolIds = await catalogToolIds();
  switch (shell) {
    case 'bash': return bashScript(toolIds);
    case 'zsh': return zshScript(toolIds);
    case 'fish': return fishScript(toolIds);
  }
}
