// SPDX-License-Identifier: MPL-2.0
/**
 * `lolly pack` / `lolly icons` - build a Linux package (RPM) from the terminal.
 * The packager entry point (plan 197 M2): offline, deterministic and
 * guideline-clean output a spec author can call from %build or an OBS source
 * service. `lolly icons` is the dedicated verb for the single most common chore
 * (an app SVG -> a hicolor icon package); `lolly pack --type=font` builds a font
 * package. Both honour SOURCE_DATE_EPOCH for reproducible bytes.
 *
 * Hermetic by construction: neither path rasterises or reaches the network, so a
 * network-less build root (OBS) produces identical output. `--hermetic` (default
 * on) is the promise that stays true as richer recipes arrive.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { basename } from 'node:path';
import { buildLinuxPack, buildHomeTarball, type RpmMeta, type IconSource, type FontFile } from '@lolly/engine';
import { EXIT, usageError } from './exit-codes.ts';
import { note, writeOut } from './output.ts';

type Flags = Record<string, string>;

const readBytes = async (p: string): Promise<Uint8Array> => new Uint8Array(await readFile(p));
const positionals = (rest: readonly string[]): string[] => rest.filter((a) => !a.startsWith('-'));
const epoch = (): number | undefined => {
  const e = process.env.SOURCE_DATE_EPOCH;
  return e && /^\d+$/.test(e) ? Number(e) : undefined;
};

/** Build the shared RpmMeta from flags; name + license are required. */
function metaFromFlags(flags: Flags): RpmMeta {
  const name = flags.name;
  if (!name) throw usageError('missing --name=<package-name>', 'MISSING_ARGUMENT');
  const license = flags.license;
  if (!license) throw usageError('missing --license=<SPDX> (e.g. OFL-1.1, CC-BY-4.0)', 'MISSING_ARGUMENT');
  const version = flags.version || '1.0';
  const release = flags.release || '1';
  const meta: RpmMeta = {
    name, version, release, license,
    summary: flags.summary || name,
    description: flags.description,
    vendor: flags.vendor,
    url: flags.url,
    group: flags.group,
    buildEpoch: epoch(),
  };
  if (flags.author) {
    meta.changelog = [{ time: epoch(), author: flags.author, text: flags.changelog || '- Package generated by Lolly.' }];
  }
  return meta;
}

/** Write the package to --output (and say where), or to stdout when piped. */
async function emit(rpm: Uint8Array, flags: Flags, defaultName: string): Promise<number> {
  const out = flags.output;
  if (out) {
    await writeFile(out, rpm);
    note(`wrote ${out} (${rpm.length} bytes)`);
  } else if (process.stdout.isTTY) {
    // Don't spew binary onto a terminal; write a sensibly-named file instead.
    await writeFile(defaultName, rpm);
    note(`wrote ${defaultName} (${rpm.length} bytes)`);
  } else {
    await writeOut(rpm);
  }
  return EXIT.OK;
}

/** `lolly icons <a.svg> [b.svg …] --name --version --license [--id] [--symbolic=x.svg] [--output]` */
export async function iconsCli(rest: readonly string[], flags: Flags): Promise<number> {
  const svgs = positionals(rest);
  if (svgs.length === 0) throw usageError('usage: lolly icons <icon.svg> […] --name=<pkg> --license=<SPDX> [--output=x.rpm]', 'MISSING_ARGUMENT');
  const meta = metaFromFlags(flags);

  const symbolicSvg = flags.symbolic ? await readBytes(flags.symbolic) : undefined;
  const icons: IconSource[] = [];
  for (const path of svgs) {
    const id = svgs.length === 1 && flags.id ? flags.id : basename(path).replace(/\.svg$/i, '');
    icons.push({ id, svg: await readBytes(path), ...(symbolicSvg && svgs.length === 1 ? { symbolicSvg } : {}) });
  }
  const rpm = await buildLinuxPack({ type: 'app-icons', meta, icons });
  return emit(rpm, flags, `${meta.name}-${meta.version}-${meta.release}.noarch.rpm`);
}

/**
 * `lolly pack --type=font <font.ttf …> --name --license [--foundry] [--appstream-id] [--output]`
 * `lolly pack --type=generic <file …> --dest=/usr/share/… --name --license [--target=rpm|tar.gz]`
 *   - the release-manager path: wrap already-rendered files at a declared install path.
 */
export async function packCli(rest: readonly string[], flags: Flags): Promise<number> {
  const type = flags.type || 'font';
  const paths = positionals(rest);

  if (type === 'font') {
    if (paths.length === 0) throw usageError('usage: lolly pack --type=font <font.ttf> […] --name=<pkg> --license=<SPDX> [--foundry=<dir>] [--output=x.rpm]', 'MISSING_ARGUMENT');
    const meta = metaFromFlags(flags);
    const fonts: FontFile[] = [];
    for (const p of paths) fonts.push({ name: basename(p), data: await readBytes(p) });
    // Opt into AppStream (software-centre listing) with --appstream-id + --font-family.
    const appstream = flags['appstream-id']
      ? {
          id: flags['appstream-id'],
          fontFamilies: (flags['font-family'] || meta.summary || meta.name).split(',').map((s) => s.trim()).filter(Boolean),
          ...(flags['metadata-license'] ? { metadataLicense: flags['metadata-license'] } : {}),
        }
      : undefined;
    const rpm = await buildLinuxPack({ type: 'font', meta, foundry: flags.foundry, fonts, appstream });
    return emit(rpm, flags, `${meta.name}-${meta.version}-${meta.release}.noarch.rpm`);
  }

  if (type === 'generic') {
    if (paths.length === 0) throw usageError('usage: lolly pack --type=generic <file> […] --dest=<install-dir> --name=<pkg> --license=<SPDX> [--target=rpm|tar.gz] [--output]', 'MISSING_ARGUMENT');
    const dest = flags.dest;
    if (!dest) throw usageError('missing --dest=<install-dir> (e.g. /usr/share/backgrounds/acme)', 'MISSING_ARGUMENT');
    const dir = dest.replace(/\/+$/, '');
    const files: { path: string; data: Uint8Array }[] = [];
    for (const p of paths) files.push({ path: `${dir}/${basename(p)}`, data: await readBytes(p) });
    if ((flags.target || 'rpm') === 'tar.gz') {
      const name = flags.name || 'lolly-pack';
      const targz = buildHomeTarball(files);
      return emit(targz, flags, `${name}.tar.gz`);
    }
    const meta = metaFromFlags(flags);
    const rpm = await buildLinuxPack({ type: 'generic', meta, files });
    return emit(rpm, flags, `${meta.name}-${meta.version}-${meta.release}.noarch.rpm`);
  }

  throw usageError(`lolly pack: --type=${type} is not supported (use font, generic, or \`lolly icons\` for app icons)`, 'UNSUPPORTED');
}
